class Player{
    constructor(){
        this.sprite
        this.start={
            x:W/2,
            y:H-50
        }
        this.w=100;
        this.h=30;
    }
    controls(){
        if(keyIsDown(KEYS.A)){
            this.goLeft()
        }
        if(keyIsDown(KEYS.D)){
            this.goRight()
        }
    }
    goLeft(){
        this.sprite.velocity.x-=3
    }
    goRight(){
        this.sprite.velocity.x+=3
    }
    setup(){
        this.sprite=this.makePaddle(this.start.x,this.start.y,this.w,this.h)
    }
    draw(balls){
        this.controls()
        this.sprite.bounce(balls.group);
    }
    makePaddle(x,y,w,h){
        let tempPaddle=createSprite(x,y,w,h);
        tempPaddle.shapeColor="red";
        tempPaddle.mass=100
        tempPaddle.friction=0.2
        return tempPaddle;
    }
}